---
image:
    file: Dockerfile

tasks:
    - name: Yarn install
      init: yarn install
      command: sleep 1 && gp sync-done yarn-install
    - name: Yarn App Server
      init: echo "Starting app server"
      command: |
          gp sync-await yarn-install &&
          yarn dev

vscode:
    extensions:
        - kimlimjustin.jsdoc-generator

        - esbenp.prettier-vscode

        - orta.vscode-jest

# Ports config
ports:
    - port: 3000
      onOpen: open-preview
    - port: 6080
      onOpen: open-browser
    - port: 5900
      onOpen: ignore

# # GitHub Prebuilds
# github:
#     prebuilds:
#         master: true
#         branches: true
#         pullRequests: true
#         pullRequestsFromForks: true
#         addComment: false
#         addBadge: true
#         addLabel: prebuilt-in-gitpod